# Site settings
title: 闪闪的成长日记
SEOTitle: 闪闪的成长日记
header-img: img/home-bg.jpg
email: kmy10489871@gmail.com
description: "她是一个活泼可爱的家养小精灵"
keyword: "闪闪，Cabbage Daddy"
url: "https://cabbagedaddy.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'





# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
source: /Users/wangwei/Documents/GitHub/www
destination: /Users/wangwei/Sites
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Serving
detach: true
port: 4000
host: 127.0.0.1


# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important








# Sidebar settings
sidebar: false                           # whether or not using Sidebar.
sidebar-about-description: "吃了睡，睡了吃，无拘无束"
sidebar-avatar: /img/avatar-hux.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`







